### ISSUE TITLE
Buses won't uses the internet

### ISSUE THREAD

**Issue by DrDustwolf** [billthefarmer/buses#1]
Buses doesn't connect itself to the internet. The 2 following consequences result out of this causation.

![Screenshot_20231215-160615_Einstellungen](https://github.com/billthefarmer/buses/assets/14179460/5e049c47-c2aa-4fd7-b939-5e379ec79ebd)

![Screenshot_20231215-160624_Einstellungen](https://github.com/billthefarmer/buses/assets/14179460/35a55f8c-5362-4959-8b5b-482100a59e47)

1️⃣: HTTP error fetching URL

I get this error: "HTTP error fetching URL" everytime I perform a search and tap on one of the entries of the search results that show up.

![Screenshot_20231215-151445_Buses](https://github.com/billthefarmer/print/assets/14179460/8928f14b-b475-4909-8852-cd1daa901f87)

![Screenshot_20231215-151453_Buses](https://github.com/billthefarmer/print/assets/14179460/564fef41-237b-418b-8a6f-4b71c0540d18)

![Screenshot_20231215-151502_Buses](https://github.com/billthefarmer/print/assets/14179460/692f4f40-41f8-4d09-87f7-2fed79531ec7)

2️⃣:
When I click on the crosshair for location search I get the following message:
Search Results for 'BOX(*Coordinates*)'. But nothing more no actual search results.

![Screenshot_20231215-160436_Buses](https://github.com/billthefarmer/buses/assets/14179460/55096753-8b35-428a-8172-a8e2c08c71c7)

Additional Informations:
Device: Shift6mq
OS: LineageOS Version: 20-20231202-microG-axolotl (Android 13)
Buses Version: 1.06

https://www.shiftphones.com/en/shift6mq/

**Comment by billthefarmer** [comment]
I can reproduce the first HTTP error, but tapping on the bus stop shown in that image gives buses from that stop.

![Screenshot_20231215-170234_Buses 1](https://github.com/billthefarmer/buses/assets/3448386/a0f1eac1-fbad-4f12-9a6a-7b89b9247900)

The app relies on web scraping the responses it gets from `https://nextbuses.mobi` to give a better user experience, so it is dependent on the site not changing the responses. Having said that, I can't see anything wrong with the URL, so I will have to investigate. Tapping on the map in Swansea as shown in your image gives...

![Screenshot_20231215-171309_Buses 1](https://github.com/billthefarmer/buses/assets/3448386/a8344813-3577-4c98-9de0-c3774c752c48)

**Comment by billthefarmer** [comment]
OK, that should be fixed in the next version.
